# Generated by Django 2.1 on 2018-09-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='ruta_price',
            field=models.CharField(default=225, max_length=250),
            preserve_default=False,
        ),
    ]
