# Generated by Django 2.1 on 2018-09-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_ruta_ruta_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='ruta_map',
            field=models.URLField(blank='True', null='True'),
            preserve_default='True',
        ),
    ]
